[server]
enableStaticServing = true

[theme]

primaryColor = '#4b2e83' # Purple

backgroundColor = '#b7a57a' # Gold

secondaryBackgroundColor = '#85754d' # Metallic Gold

textColor = '#330066' # Purple

[client]
showSidebarNavigation = false